# WORKFLOW
name: 'Custom Workflow'
on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]
permissions:
    contents: read
    issues: read
    actions: read
    discussions: read

# review dependencies
# Source repository: https://github.com/actions/dependency-review-action
# Public documentation: https://docs.github.com/en/code-security/supply-chain-security/understanding-your-software-supply-chain/about-dependency-review#dependency-review-enforcement

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v3
      - name: 'Dependency Review'
        uses: actions/dependency-review-action@v2